env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/jsx-filename-extension:
    - error
    - extensions:
      - .tsx
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': error
  import/no-unresolved: off
  import/extensions: off
  react/jsx-one-expression-per-line: off
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
  jsx-a11y/media-has-caption: off
  jsx-a11y/alt-text: off
  no-restricted-syntax: off
  default-case: off
  max-len: off
  no-mixed-operators: off
  jsx-a11y/label-has-associated-control: off
  object-curly-newline: off
  no-bitwise: off
  no-alert: off
